services:
  mongodb:
    build:
      context: ./MongoDB
      dockerfile: Dockerfile
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: appdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - mongo_network
      

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    networks:
      - mongo_network

  spring-boot-app:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: spring_boot_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongodb:27017/appdb?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./logs/APIGenerated:/var/log/app
    networks:
      - mongo_network
      
  frontend:
    build:
      context: ./Frontend/react
      dockerfile: Dockerfile
    container_name: frontend_container
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    depends_on:
      - spring-boot-app
    networks:
      - mongo_network
      
  web:
    image: nginx:alpine
    container_name: web_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - spring-boot-app
      - otel-collector
    networks:
      - mongo_network

  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"   # UI Jaeger
      - "4317:4317"     # OTLP gRPC ingest
      - "4318:4318"     # OTLP HTTP ingest (optionnel)
    networks:
      - mongo_network

  otel-collector:
      image: otel/opentelemetry-collector-contrib:0.111.0
      command: [ "--config=/etc/otelcol/config.yaml" ]
      volumes:
        - ./otelcol.yaml:/etc/otelcol/config.yaml:ro
      ports:
        - "4319:4318"
      depends_on:
        - jaeger
      networks:
        - mongo_network

networks:
  mongo_network:
    driver: bridge

